### ISSUE TITLE
Accessing Catalogue

### ISSUE THREAD

**Issue by SEALCOOL13** [stremio-arc/arc#1]
How do I see the streams listed? Can't find an option on the discover/home page and doesn't show up when I search anything?
Point me in the right direction please.
Thanks in advance.

**Comment by stremio-arc** [comment]
For TV channels, you can see the listed channels in Discover tab categorized by country.

For movies/shows, you can use the default cinemeta addon and select a movie / show, if a stream is available it will show up.
